routes/web.php
<?php

Route::get('/', 'Site\PostController@index');

Route::get('/read/{post}', 'Site\PostController@show')->name('post.show');

Route::get('/category/{category}', 'Site\PostController@category')->name('category');

Route::get('/user/{user}', 'Site\PostController@user')->name('user');

Route::get('/tag/{tag}', 'Site\PostController@tag')->name('tag');

Route::get('testinfo', function(){
    echo phpinfo();
});

Route::post('contact', 'Site\ContactController@contactPost')->name('contact.store');

Auth::routes();

Route::get('/auth/activate', 'Auth\ActivationController@activate')->name('auth.activate');

Route::get('/auth/activate/resend','Auth\ActivationResendController@showResendForm');
Route::post('/auth/activate/resend', 'Auth\ActivationResendController@resend')->name('auth.activate.resend');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('add-to-log', 'HomeController@myTestAddToLog');
Route::get('logActivity', 'HomeController@logActivity');

// Admin Area
Route::resource('/dashboard/post', 'Admin\Site\PostController');

Route::get('/api/postcollection', 'Admin\Site\PostController@postCollection')->name('post.collection');

app/Models/Actor/User.php
<?php

namespace App\Models\Actor;

use App\Models\Site\Post;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'slug', 'email', 'password', 'active', 'activation_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function scopeByActivationColumns(Builder $builder, $email, $token)
    {
        return $builder->where('email', $email)->where('activation_token', $token);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function gravatar()
    {
        $email = $this->email;
        $default = "https://api.adorable.io/avatars/285/putraranji.png";
        $size = 40;

        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?d=" . urlencode( $default ) . "&s=" . $size;
    }

    public function getBioHtmlAttribute($value)
    {
        return $this->biography ? Markdown::convertToHtml(e($this->biography)) : NULL;
    }
}

app/Models/Site/Article.php
<?php

namespace App\Models\Site;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //
}

app/Models/Site/Category.php
<?php

namespace App\Models\Site;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Models/Site/Contact.php
<?php

namespace App\Models\Site;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    public $table = 'contacts';

    public $fillable = ['name','email','phone','message'];
}

app/Models/Site/Log/LogActivity.php
<?php

namespace App\Models\Site\Log;

use Illuminate\Database\Eloquent\Model;

class LogActivity extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'subject', 'url', 'method', 'ip', 'agent', 'user_id'
    ];
}

app/Models/Site/Post.php
<?php

namespace App\Models\Site;

use Carbon\Carbon;
use App\Models\Actor\User;
use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{
    protected $dates = ['published_at'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
    
    public function getImageUrlAttribute($value)
    {
        $imageUrl = "";
        if (! is_null($this->image)) {
            $imageDir = public_path() . "/img/posts/" . $this->image;
            if (file_exists($imageDir)) {
                $imageUrl = asset("img/posts/" . $this->image);
            }
        }

        return $imageUrl;
    }

    public function getDateAttribute($value)
    {
        return is_null($this->published_at) ? '' : $this->published_at->toFormattedDateString();
    }

    public function getBodyHtmlAttribute($value)
    {
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    public function scopeLatestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }


}

app/Models/Site/Tag.php
<?php

namespace App\Models\Site;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/Site/PostController.php
<?php

namespace App\Http\Controllers\Admin\Site;

use App\Models\Site\Post;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Http\Resources\Site\Admin\PostResource;
use Yajra\DataTables\Facades\DataTables;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.post.index');
    }

    public function postCollection()
    {
        $posts = Post::all();
        return DataTables::of($posts)
            ->addColumn('action', function($posts) {
                return 
                '<a onclick="editForm('. $posts->id .')" class="btn btn-primary btn-sm mr-1"><i class="far fa-edit" style="color:white"></i></a>'.
                '<a onclick="deleteData('. $posts->id .')" class="btn btn-danger btn-sm"><i class="far fa-trash-alt" style="color:white"></i></a>';
            })->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Site/ArticlesController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Site\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\Site\ArticleResource;

class ArticlesController extends Controller
{
    protected $limit = 5;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth', ['except' => ['index', 'show']]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Get articles
        $articles = Article::orderBy('created_at', 'desc')->paginate($this->limit);

        // Return collection of articles as a resource
        return ArticleResource::collection($articles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = $request->isMethod('put') ? Article::findOrFail($request->article_id) : new Article;
        $article->id = $request->input('article_id');
        $article->title = $request->input('title');
        $article->body = $request->input('body');

        if ($article->save()) {
            return new ArticleResource($article);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Get single article
        $article = Article::findOrFail($id);
        // Return single article as resource
        return new ArticleResource($article);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Get single article
        $article = Article::findOrFail($id);
        if($article->delete()){
            return new ArticleResource($article);
        }
    }
}

app/Http/Controllers/Site/ContactController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{

    /**
    * Show the application dashboard.
    *
    * @return \Illuminate\Http\Response
    */
   public function contactPost(Request $request)
   {
       $this->validate($request, [
        'name' => 'required',
        'email' => 'required|email',
        'phone' => 'required',
        'message' => 'required'
        ]);

       Contact::create($request->all());

       return back()->with('success', 'Thanks for contacting us!');
   }
}

app/Http/Controllers/Site/PostController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Site\Tag;
use App\Models\Site\Post;
use App\Models\Actor\User;
use Illuminate\Http\Request;
use App\Models\Site\Category;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class PostController extends Controller
{
    protected $limit = 6;

    public function index()
    {
        $categories = Category::with(['posts' => function($query){
            $query->published();
        }])->orderBy('title', 'asc')->get();

        $posts = Post::with('user')
                    ->latestFirst()
                    ->published()
                    ->simplePaginate($this->limit);

        return view('site.index', compact('posts', 'categories'));
    }

    public function category(Category $category)
    {
        $categories = Category::with(['posts' => function($query){
            $query->published();
        }])->orderBy('title', 'asc')->get();

        $posts = $category->posts()
                    ->with('user')
                    ->latestFirst()
                    ->published()
                    ->paginate($this->limit);

        return view('site.index', compact('posts', 'categories'));
    }

    public function tag(Tag $tag)
    {
        $posts = $tag->posts()
                    ->with('user')
                    ->latestFirst()
                    ->published()
                    ->paginate($this->limit);

        return view('site.index', compact('posts'));
    }

    public function user(User $user)
    {
        $userName = $user->first_name;

        $categories = Category::with(['posts' => function($query){
            $query->published();
        }])->orderBy('title', 'asc')->get();

        $posts = $user->posts()
                    ->with('category')
                    ->latestFirst()
                    ->published()
                    ->paginate($this->limit);

        return view('site.index', compact('posts', 'userName', 'categories'));
    }

    public function show(Post $post)
    {

        $ids = Session::get('ids') ? Session::get('ids') : [];
        if (!in_array($post->id, $ids)) 
        {
            $post->increment('view_count');
            $ids[] = $post->id;
            Session::put('ids', $ids);
        }

        $relatedPosts = Post::whereHas('tags', function($q) use ($post){
            return $q->whereIn('name', $post->tags->pluck('name'));
        })->published()->take(5)->where('id', '!=', $post->id)->get();

        return view('site.show', compact('post', 'relatedPosts'));
    }
}

resources/views/site/index.blade.php
@extends('layouts.main')
@section('title', 'Latest Articles')
@section('content')

    <!-- Header -->
    <header class="masthead bg-primary text-white text-center">
      <div class="container">
        <img class="img-fluid mb-5 d-block mx-auto" src="img/profile.png" alt="">
        <h1 class="text-uppercase mb-0">L56</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">Web Developer - Graphic Artist - User Experience Designer</h2>
      </div>
    </header>

    <!-- article Grid Section -->
    <section class="article" id="articles">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Latest Articles</h2>
        <hr class="star-dark mb-5">
        <div class="row">
          @foreach ($posts as $post)
            <div class="col-md-6 col-lg-4">
              <a class="article-item d-block mx-auto" href="#article-modal-{{$post->id}}">
                <div class="article-item-caption d-flex position-absolute h-100 w-100">
                  <div class="article-item-caption-content my-auto w-100 text-center text-white">
                    <i class="fas fa-search-plus fa-3x"></i>
                  </div>
                </div>
                @if ($post->image)
                  <img class="img-fluid" src="{{$post->image_url}}" alt="">
                  <p class="text-center"><span class="badge badge-danger badge-circle"><i class="fa fa-folder"></i> {{ $post->category->title }}</span></p>
                @else
                  <img class="img-fluid" src="/img/posts/default.png" alt=""> 
                  <p class="text-center"><span class="badge badge-danger badge-circle"><i class="fa fa-folder"></i> {{ $post->category->title }}</span></p>   
                @endif
              </a>
            </div>
          @endforeach
        </div>
        <div>{{ $posts->links() }}</div>
      </div>
    </section>

    <!-- About Section -->
    <section class="bg-primary text-white mb-0" id="about">
      <div class="container">
        <h2 class="text-center text-uppercase text-white">About</h2>
        <hr class="star-light mb-5">
        <div class="row">
          <div class="col-lg-4 ml-auto">
            <p class="lead">Laravel 5.6 or what ever</p>
          </div>
          <div class="col-lg-4 mr-auto">
            <p class="lead">Laravel 5.6 or what ever</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
   @include('site.contact.index')

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>

    <!-- article Modals -->

    <!-- article Modal 1 -->
    @foreach ($posts as $post)
    <div class="article-modal mfp-hide" id="article-modal-{{$post->id}}">
      <div class="article-modal-dialog bg-white">
        <a class="close-button d-none d-md-block article-modal-dismiss" href="#">
          <i class="fa fa-3x fa-times"></i>
        </a>
        <div class="container text-center">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2 class="text-secondary text-uppercase mb-0">{{$post->title}}</h2>
              <hr class="star-dark mb-5">
              @if ($post->image)
                <img class="img-fluid" src="{{$post->image_url}}" alt="">
                @else
                <img class="img-fluid" src="/img/posts/default.png" alt="">    
                @endif
              <div class="mb-3 mt-3" style="justify-content:center"><strong>Posted by</strong> <span class="badge badge-dark">{{ $post->user->first_name }}</span> | <span><i class="far fa-clock"></i> {{ $post->date }}</span> | <span><i class="far fa-folder"></i> {{ $post->category->title }}</span></div>
              <p class="mb-5">{{ $post->excerpt }}</p>
              <a class="btn btn-primary btn-lg rounded-pill" href="{{route('post.show', $post->slug)}}">
                <i class="fa fa-close"></i>
                Read more</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    @endforeach

@endsection
    

resources/views/site/show.blade.php
@extends('layouts.main')
@section('title')
{{$post->title}}
@endsection
@section('content')
<div class="container" style="margin-top:100px">
    <div class="row">
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 order-lg-1 mb-4">
                        <div class="card">
                            <!-- user profile image -->
                            <img class="card-img-top" src="{{ $post->user->gravatar() }}" alt="{{ $post->user->first_name }} {{ $post->user->last_name }}">
                            <div class="card-body text-center">
                                <!-- user name -->
                                <h4 class="card-title">{{ $post->user->first_name }} {{ $post->user->last_name }}</h4>
                                <!-- job title / comany name -->
                                <p class="card-text text-muted">{{ $post->user->work }}</p>
                                <p class="card-text text-muted">Bio: {!! $post->user->bio_html !!}</p>
                                <?php $postCount = $post->user->posts()->published()->count(); ?>
                                <p class="card-text text-muted">{{ $postCount }}  {{ str_plural('post', $postCount) }}</p>
                                <!-- social profile links -->
                                <a href="#" class="social twitter"><i class="fab fa-fw fa-twitter"></i></a>
                                <a href="#" class="social facebook"><i class="fab fa-fw fa-facebook"></i></a>
                                <a href="#" class="social google-plus"><i class="fab fa-fw fa-google-plus"></i></a>
                                <a href="#" class="social linkedin"><i class="fab fa-fw fa-linkedin"></i></a>
                                <!-- CTA button -->
                                <p class="mt-4"><a href="{{ url('/') }}#contact" class="btn btn-primary">Contact me!</a></p>
                            </div>
                        </div>
                        @include('layouts.sidebar')
                    </div>
                    <div class="col-lg-9">
                        <div class="blog-grids">
                            <div class="grid">
                                <div class="entry-media">
                                    @if ($post->image)
                                    <img src="{{ $post->image_url }}" alt="{{ $post->title }}">                                        
                                    @endif
                                </div>
                                <div class="entry-body">
                                    <h2>{{ $post->title }}</h2>
                                    <span class="cat">BY <a href="{{ route('user', $post->user->slug)}}">{{ $post->user->first_name }}</a></span>
                                    <span class="cat">under <a href="{{ route('category', $post->category->slug) }}">{{ $post->category->title }}</a></span>
                                    <p>{!! $post->body_html !!}</p>
                                    <div class="row">
                                        <div class="col-sm">
                                        Posted {{ $post->date }}
                                        </div>
                                        <div class="col-sm">
                                            Tagged :
                                           @foreach ($post->tags as $item)
                                                <a href="{{ route('tag', $item->slug) }}" class="badge badge-secondary">{{ $item->name }}</a>
                                           @endforeach
                                        </div>
                                    </div>
                                    <hr style="border-style:dashed;">
                                    <div class="container">
                                        <div class="row">
                                            <h3 class="badge badge-primary">Related Articles</h3>
                                            @if ($relatedPosts->count() > 0)
                                            <div class="col-md-12">
                                                @foreach ($relatedPosts as $post)
                                                <div>
                                                    <h3><a href="{{ route('post.show', $post->slug) }}">{{ $post->title }}</a></h3>
                                                    <p>{{ str_limit($post->excerpt, 150) }} - <span class="badge badge-secondary">{{ $post->date }}</span></p>
                                                </div>
                                                @endforeach
                                            <div>
                                            @else
                                             <div class="col-md-12">
                                                 <p>There's no related article could be displayed at this moment</p>
                                             </div>   
                                            @endif
                                        </div>
                                        </div>
                                    </div>  
                                  </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>
@endsection